name: PR Comment Analysis
on:
  schedule:
    # Run every month on the 1st at 2 AM UTC
    - cron: '0 2 1 * *'
  workflow_dispatch:  # Allow manual triggering
permissions:
  contents: read
  pull-requests: read
jobs:
  analyze-pr-comments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run PR comment analysis and create results file
      id: analysis
      run: |
        # Create the results file
        echo "# PR Comment Analysis Report" > pr_comment_analysis_$(date +%Y-%m-%d).md
        echo "" >> pr_comment_analysis_$(date +%Y-%m-%d).md
        echo "**Analysis Date:** $(date)" >> pr_comment_analysis_$(date +%Y-%m-%d).md
        echo "**Repository:** ${{ github.repository }}" >> pr_comment_analysis_$(date +%Y-%m-%d).md
        echo "" >> pr_comment_analysis_$(date +%Y-%m-%d).md
        echo "## Results" >> pr_comment_analysis_$(date +%Y-%m-%d).md
        echo '```' >> pr_comment_analysis_$(date +%Y-%m-%d).md
        # Run the analysis and capture output
        python scripts/pr_comment_analyzer.py \
          --repo "https://github.com/${{ github.repository }}" \
          --token "${{ secrets.GITHUB_TOKEN }}" >> pr_comment_analysis_$(date +%Y-%m-%d).md
        echo '```' >> pr_comment_analysis_$(date +%Y-%m-%d).md
    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pr-comment-analysis-${{ github.run_number }}
        path: pr_comment_analysis_*.md
        retention-days: 365
    - name: Create summary
      run: |
        echo "## PR Comment Analysis Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Analysis completed for repository: **${{ github.repository }}**" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo ":bar_chart: **Results saved as artifact:** pr-comment-analysis-${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo ":date: **Next scheduled run:** 30 days from now" >> $GITHUB_STEP_SUMMARY
